### ISSUE TITLE
does not enter the web app

### ISSUE THREAD

**Issue by AAbeijon1** [tanushdhamija/yolov7-dashboard#1]
I'm sorry for the inconvenience.
I follow the tututial as you describe it. dependencies are installed correctly. and !streamlit run app.py is running without errors but the http does not show me anything

thank you so much
ps: sorry for my english is not too good

**Comment by tanushdhamija** [comment]
Hi,
What's the exact error? Once the streamlit app is running, what do you see when you go to localhost:8501? Note that it should also open the webpage automatically. I just ran it and here's what you should see on the terminal and the webpage running with the local video option:

![terminal](https://github.com/tanushdhamija/yolov7-dashboard/assets/62652020/1070e593-4c97-47e6-bece-a71b619d7aa0)


![webpage](https://github.com/tanushdhamija/yolov7-dashboard/assets/62652020/674c248b-2c73-437d-b541-f2696d8bf26d)
